# Generated by Django 6.0 on 2026-01-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('realm_level', models.IntegerField(unique=True)),
                ('base_xp', models.IntegerField()),
                ('max_lifespan', models.IntegerField()),
                ('intro_text', models.TextField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserCultivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_level', models.IntegerField(default=0)),
                ('sub_level', models.IntegerField(default=1)),
                ('current_xp', models.IntegerField(default=0)),
                ('platform_age_years', models.IntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
