# Generated by Django 6.0 on 2026-03-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercultivation',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
    ]
